import type { ChallengeConfig, ChallengePlayer } from "@/lib/games/budget-challenge-types";

export const budgetChallengeConfig: ChallengeConfig = {
  id: "lck-2026-15-dollar",
  title: "15달러 챌린지",
  description: "LCK 주전 50명 중 예산 15달러로 나만의 베스트 5를 완성해 보세요.",
  budget: 15,
  mode: "position-lock",
  slots: [
    { position: "TOP", requiredCount: 1 },
    { position: "JUNGLE", requiredCount: 1 },
    { position: "MID", requiredCount: 1 },
    { position: "ADC", requiredCount: 1 },
    { position: "SUPPORT", requiredCount: 1 },
  ],
  shareWatermark: "LCK Rating",
};

export const budgetChallengePlayers: ChallengePlayer[] = [
  { id: "zeus", name: "Zeus", shortLabel: "Zeus", team: "HLE", position: "TOP", price: 5, image: "/icons/leagues/lck.webp", active: true, order: 1 },
  { id: "kiin", name: "Kiin", shortLabel: "Kiin", team: "GEN", position: "TOP", price: 5, image: "/icons/leagues/lck.webp", active: true, order: 2 },
  { id: "doran", name: "Doran", shortLabel: "Doran", team: "T1", position: "TOP", price: 4, image: "/icons/leagues/lck.webp", active: true, order: 3 },
  { id: "kingen", name: "Kingen", shortLabel: "Kingen", team: "NS", position: "TOP", price: 4, image: "/icons/leagues/lck.webp", active: true, order: 4 },
  { id: "siwoo", name: "Siwoo", shortLabel: "Siwoo", team: "DK", position: "TOP", price: 3, image: "/icons/leagues/lck.webp", active: true, order: 5 },
  { id: "perfect", name: "PerfecT", shortLabel: "PerfecT", team: "KT", position: "TOP", price: 3, image: "/icons/leagues/lck.webp", active: true, order: 6 },
  { id: "rich", name: "Rich", shortLabel: "Rich", team: "KRX", position: "TOP", price: 2, image: "/icons/leagues/lck.webp", active: true, order: 7 },
  { id: "casting", name: "Casting", shortLabel: "Casting", team: "BRO", position: "TOP", price: 2, image: "/icons/leagues/lck.webp", active: true, order: 8 },
  { id: "clear", name: "Clear", shortLabel: "Clear", team: "BFX", position: "TOP", price: 1, image: "/icons/leagues/lck.webp", active: true, order: 9 },
  { id: "dudu", name: "DuDu", shortLabel: "DuDu", team: "DNS", position: "TOP", price: 1, image: "/icons/leagues/lck.webp", active: true, order: 10 },

  { id: "canyon", name: "Canyon", shortLabel: "Canyon", team: "GEN", position: "JUNGLE", price: 5, image: "/icons/leagues/lck.webp", active: true, order: 1 },
  { id: "oner", name: "Oner", shortLabel: "Oner", team: "T1", position: "JUNGLE", price: 5, image: "/icons/leagues/lck.webp", active: true, order: 2 },
  { id: "kanavi", name: "Kanavi", shortLabel: "Kanavi", team: "HLE", position: "JUNGLE", price: 4, image: "/icons/leagues/lck.webp", active: true, order: 3 },
  { id: "lucid", name: "Lucid", shortLabel: "Lucid", team: "DK", position: "JUNGLE", price: 4, image: "/icons/leagues/lck.webp", active: true, order: 4 },
  { id: "cuzz", name: "Cuzz", shortLabel: "Cuzz", team: "KT", position: "JUNGLE", price: 3, image: "/icons/leagues/lck.webp", active: true, order: 5 },
  { id: "pyosik", name: "Pyosik", shortLabel: "Pyosik", team: "DNS", position: "JUNGLE", price: 3, image: "/icons/leagues/lck.webp", active: true, order: 6 },
  { id: "krx_willer", name: "Willer", shortLabel: "Willer", team: "KRX", position: "JUNGLE", price: 2, image: "/icons/leagues/lck.webp", active: true, order: 7 },
  { id: "gideon", name: "GIDEON", shortLabel: "GIDEON", team: "BRO", position: "JUNGLE", price: 2, image: "/icons/leagues/lck.webp", active: true, order: 8 },
  { id: "raptor", name: "Raptor", shortLabel: "Raptor", team: "BFX", position: "JUNGLE", price: 1, image: "/icons/leagues/lck.webp", active: true, order: 9 },
  { id: "ns_willer", name: "Willer", shortLabel: "Willer", team: "NS", position: "JUNGLE", price: 1, image: "/icons/leagues/lck.webp", active: true, order: 10 },

  { id: "faker", name: "Faker", shortLabel: "Faker", team: "T1", position: "MID", price: 5, image: "/icons/leagues/lck.webp", active: true, order: 1 },
  { id: "chovy", name: "Chovy", shortLabel: "Chovy", team: "GEN", position: "MID", price: 5, image: "/icons/leagues/lck.webp", active: true, order: 2 },
  { id: "zeka", name: "Zeka", shortLabel: "Zeka", team: "HLE", position: "MID", price: 4, image: "/icons/leagues/lck.webp", active: true, order: 3 },
  { id: "showmaker", name: "ShowMaker", shortLabel: "ShowMaker", team: "DK", position: "MID", price: 4, image: "/icons/leagues/lck.webp", active: true, order: 4 },
  { id: "scout", name: "Scout", shortLabel: "Scout", team: "NS", position: "MID", price: 3, image: "/icons/leagues/lck.webp", active: true, order: 5 },
  { id: "bdd", name: "Bdd", shortLabel: "Bdd", team: "KT", position: "MID", price: 3, image: "/icons/leagues/lck.webp", active: true, order: 6 },
  { id: "clozer", name: "Clozer", shortLabel: "Clozer", team: "DNS", position: "MID", price: 2, image: "/icons/leagues/lck.webp", active: true, order: 7 },
  { id: "ucal", name: "ucal", shortLabel: "ucal", team: "KRX", position: "MID", price: 2, image: "/icons/leagues/lck.webp", active: true, order: 8 },
  { id: "fisher", name: "Fisher", shortLabel: "Fisher", team: "BRO", position: "MID", price: 1, image: "/icons/leagues/lck.webp", active: true, order: 9 },
  { id: "vicla", name: "VicLa", shortLabel: "VicLa", team: "BFX", position: "MID", price: 1, image: "/icons/leagues/lck.webp", active: true, order: 10 },

  { id: "ruler", name: "Ruler", shortLabel: "Ruler", team: "GEN", position: "ADC", price: 5, image: "/icons/leagues/lck.webp", active: true, order: 1 },
  { id: "gumayusi", name: "Gumayusi", shortLabel: "Guma", team: "HLE", position: "ADC", price: 5, image: "/icons/leagues/lck.webp", active: true, order: 2 },
  { id: "peyz", name: "Peyz", shortLabel: "Peyz", team: "T1", position: "ADC", price: 4, image: "/icons/leagues/lck.webp", active: true, order: 3 },
  { id: "aiming", name: "Aiming", shortLabel: "Aiming", team: "KT", position: "ADC", price: 4, image: "/icons/leagues/lck.webp", active: true, order: 4 },
  { id: "smash", name: "Smash", shortLabel: "Smash", team: "DK", position: "ADC", price: 3, image: "/icons/leagues/lck.webp", active: true, order: 5 },
  { id: "jiwoo", name: "Jiwoo", shortLabel: "Jiwoo", team: "KRX", position: "ADC", price: 3, image: "/icons/leagues/lck.webp", active: true, order: 6 },
  { id: "teddy", name: "Teddy", shortLabel: "Teddy", team: "BRO", position: "ADC", price: 2, image: "/icons/leagues/lck.webp", active: true, order: 7 },
  { id: "taeyoon", name: "Taeyoon", shortLabel: "Taeyoon", team: "NS", position: "ADC", price: 2, image: "/icons/leagues/lck.webp", active: true, order: 8 },
  { id: "diable", name: "Diable", shortLabel: "Diable", team: "BFX", position: "ADC", price: 1, image: "/icons/leagues/lck.webp", active: true, order: 9 },
  { id: "deokdam", name: "deokdam", shortLabel: "deokdam", team: "DNS", position: "ADC", price: 1, image: "/icons/leagues/lck.webp", active: true, order: 10 },

  { id: "keria", name: "Keria", shortLabel: "Keria", team: "T1", position: "SUPPORT", price: 5, image: "/icons/leagues/lck.webp", active: true, order: 1 },
  { id: "delight", name: "Delight", shortLabel: "Delight", team: "HLE", position: "SUPPORT", price: 5, image: "/icons/leagues/lck.webp", active: true, order: 2 },
  { id: "duro", name: "Duro", shortLabel: "Duro", team: "GEN", position: "SUPPORT", price: 4, image: "/icons/leagues/lck.webp", active: true, order: 3 },
  { id: "lehends", name: "Lehends", shortLabel: "Lehends", team: "NS", position: "SUPPORT", price: 4, image: "/icons/leagues/lck.webp", active: true, order: 4 },
  { id: "career", name: "Career", shortLabel: "Career", team: "DK", position: "SUPPORT", price: 3, image: "/icons/leagues/lck.webp", active: true, order: 5 },
  { id: "kellin", name: "Kellin", shortLabel: "Kellin", team: "BFX", position: "SUPPORT", price: 3, image: "/icons/leagues/lck.webp", active: true, order: 6 },
  { id: "pollu", name: "Pollu", shortLabel: "Pollu", team: "KT", position: "SUPPORT", price: 2, image: "/icons/leagues/lck.webp", active: true, order: 7 },
  { id: "life", name: "Life", shortLabel: "Life", team: "DNS", position: "SUPPORT", price: 2, image: "/icons/leagues/lck.webp", active: true, order: 8 },
  { id: "andil", name: "Andil", shortLabel: "Andil", team: "KRX", position: "SUPPORT", price: 1, image: "/icons/leagues/lck.webp", active: true, order: 9 },
  { id: "namgung", name: "Namgung", shortLabel: "Namgung", team: "BRO", position: "SUPPORT", price: 1, image: "/icons/leagues/lck.webp", active: true, order: 10 },
];
